config/routes.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do

  resources :books

  # [START login]
  get "/login", to: redirect("/auth/google_oauth2")
  # [END login]

  # [START sessions]
  get "/auth/google_oauth2/callback", to: "sessions#create"

  resource :session, only: [:create, :destroy]
  # [END sessions]

  # [START user_books]
  resources :user_books, only: [:index]
  # [END user_books]

  # [START logout]
  get "/logout", to: "sessions#destroy"
  # [END logout]

  root "books#index"

end

app/models/book.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START book]
class Book < ActiveRecord::Base
  validates :title, presence: true

  attr_accessor :cover_image

  private

  # [START upload]
  after_create :upload_image, if: :cover_image

  def upload_image
    image = StorageBucket.files.new(
      key: "cover_images/#{id}/#{cover_image.original_filename}",
      body: cover_image.read,
      public: true
    )

    image.save

    update_columns image_url: image.public_url
  end
  # [END upload]

  # TODO what if the image is from the Pub/Sub job and NOT in Cloud Storage!?

  # [START delete]
  before_destroy :delete_image, if: :image_url

  def delete_image
    bucket_name = StorageBucket.key
    image_uri   = URI.parse image_url

    if image_uri.host == "#{bucket_name}.storage.googleapis.com"
      # Remove leading forward slash from image path
      # The result will be the image key, eg. "cover_images/:id/:filename"
      image_key = image_uri.path.sub("/", "")
      image     = StorageBucket.files.new key: image_key

      image.destroy
    end
  end
  # [END delete]

  # [START update]
  before_update :update_image, if: :cover_image

  def update_image
    delete_image if image_url?
    upload_image
  end
  # [END update]
end
# [END book]

app/models/user.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START user]
class User
  attr_accessor :id, :name, :image_url
end
# [END user]

app/controllers/application_controller.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class BooksController < ApplicationController

  PER_PAGE = 10

  def index
    page = params[:more] ? params[:more].to_i : 0

    @books = Book.limit(PER_PAGE).offset PER_PAGE * page
    @more  = page + 1 if @books.count == PER_PAGE
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find params[:id]
  end

  def show
    @book = Book.find params[:id]
  end

  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find params[:id]

    if @book.update book_params
      flash[:success] = "Updated Book"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  # [START create]
  def create
    @book = Book.new book_params

    @book.creator_id = current_user.id if logged_in?

    if @book.save
      flash[:success] = "Added Book"
      redirect_to book_path(@book)
    else
      render :new
    end
  end
  # [END create]

  private

  def book_params
    params.require(:book).permit :title, :author, :published_on, :description,
                                 :cover_image
  end

end

app/controllers/sessions_controller.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START create]
class SessionsController < ApplicationController

  # Handle Google OAuth 2.0 login callback.
  #
  # GET /auth/google_oauth2/callback
  def create
    user_info = request.env["omniauth.auth"]

    user           = User.new
    user.id        = user_info["uid"]
    user.name      = user_info["info"]["name"]
    user.image_url = user_info["info"]["image"]

    session[:user] = Marshal.dump user

    redirect_to root_path
  end
# [END create]

  # [START destroy]
  def destroy
    session.delete :user

    redirect_to root_path
  end
  # [END destroy]

end

app/controllers/user_books_controller.rb
# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START user_books]
class UserBooksController < ApplicationController

  PER_PAGE = 10

  before_filter :login_required

  def index
    page = params[:more] ? params[:more].to_i : 0

    @books = Book.where(creator_id: current_user.id).
                  limit(PER_PAGE).offset(PER_PAGE * page)

    @more = page + 1 if @books.count == PER_PAGE

    render "books/index"
  end

  private

  def login_required
    redirect_to root_path unless logged_in?
  end

end
# [END user_books]

app/views/books/_form.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Book</h3>

<% if @book.errors.any? %>
  <div class="errors">
    <% @book.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
<% end %>

<!-- [START multipart] -->
<%= form_for @book, :html => { :multipart => true } do |f| %>
<!-- [END multipart] -->
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :published_on, "Date Published" %>
    <%= f.date_field :published_on %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <!-- [START cover_image] -->
  <div class="form-group">
    <%= f.label :cover_image %>
    <%= f.file_field :cover_image %>
  </div>
  <!-- [END cover_image] -->
  <button class="btn btn-success" type="submit">Save</button>
<% end %>

app/views/books/_pagination_link.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<% if @more %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", books_path(more: @more) %></li>
    </ul>
  </nav>
<% end %>

app/views/books/edit.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<%= render partial: "form" %>

app/views/books/index.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Books</h3>

<%= link_to new_book_path, class: "btn btn-success btn-sm" do %>
  <i class="glyphicon glyphicon-plus"></i>
  <span>Add Book</span>
<% end %>

<% @books.each do |book| %>
  <div class="book media">
    <%= link_to book_path(book) do %>
      <div class="media-left">
        <img src="<%= book.image_url %>">
      </div>
      <div class="media-body">
        <h4><%= book.title %></h4>
        <p><%= book.author %></p>
      </div>
    <% end %>
  </div>
<% end %>

<% if @more %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", books_path(more: @more) %></li>
    </ul>
  </nav>
<% end %>

<% if @books.none? %>
  <p>No books found.</p>
<% end %>

app/views/books/new.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<%= render partial: "form" %>

app/views/books/show.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<h3>Book</h3>

<div class="btn-group">
  <%= link_to edit_book_path(@book), class: "btn btn-primary btn-sm" do %>
    <i class="glyphicon glyphicon-edit"></i>
    <span>Edit Book</span>
  <% end %>
  <%= link_to book_path(@book), class: "btn btn-danger btn-sm", method: :delete do %>
    <i class="glyphicon glyphicon-trash"></i>
    <span>Delete Book</span>
  <% end %>
</div>

<%# [START book_details] %>
<div class="media">
  <!-- [START cover] -->
  <div class="media-left">
    <img src="<%= @book.image_url %>">
  </div>
  <!-- [END cover] -->
  <div class="media-body">
    <h4><%= @book.title %> | &nbsp; <small><%= @book.published_on %></small></h4>
    <h5>By <%= @book.author || "unknown" %></h5>
    <p><%= @book.description %></p>
  </div>
</div>
<%# [END book_details] %>

app/views/layouts/application.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf - Ruby on Google Cloud Platform</title>
    <meta charset="utf-8">
    <meta name="viewset" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <div class="navbar-brand">Bookshelf</div>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Books", root_path %></li>
          <%# [START mine] %>
          <% if logged_in? %>
            <li><%= link_to "Mine", user_books_path %></li>
          <% end %>
          <%# [END mine] %>
        </ul>
        <p class="navbar-text navbar-right">
          <%# [START user_profile] %>
          <% if logged_in? %>
            <% if current_user.image_url %>
              <%= image_tag current_user.image_url, class: "img-circle", width: 24 %>
            <% end %>
            <span>
              <%= current_user.name %> &nbsp;
              <%# [START logout] %>
              <%= link_to "(logout)", logout_path %>
              <%# [END logout] %>
            </span>
          <%# [END user_profile] %>
          <% else %>
            <%# [START login] %>
            <%= link_to "Login", login_path %>
            <%# [END login] %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="container">
      <% if flash.any? %>
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>"><%= message %></div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_books/_pagination_link.html.erb
<%#
  Copyright 2015, Google, Inc.
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
%>

<% if @more %>
  <nav>
    <ul class="pager">
      <li><%= link_to "More", user_books_path(more: @more) %></li>
    </ul>
  </nav>
<% end %>